Repository sodafoundation/dashboard, pull requests merged in 2019-12, with the labels that each got.

#221 Fixed incorrect accessProtocol values in create Profile. Uppercase values to lowercase.
  src/app/business/profile/createProfile/createProfile.component.ts
Labels: Daito, bug

#223 Fixed Object listing page to match changed Backend response
  src/app/business/block/bucket-detail/bucket-detail.component.html
  src/app/business/block/bucket-detail/bucket-detail.component.ts
Labels: Daito, bug

#226 Fixes #225. Fix Display host details.
  src/app/business/block/host-detail/host-detail.component.html
  src/app/business/block/host-detail/host-detail.component.ts
  src/app/business/block/hosts.component.html
Labels: Daito, bug

#228 Fixes #227. Fixed host dropdown in volume provision service.
  src/app/business/services/dynamic-form/dynamic-form.component.html
  src/app/business/services/dynamic-form/dynamic-form.component.ts
  src/assets/business/css/site.scss
Labels: Daito, bug

#230 Fixes #229. Added Missing Label in Attach host and other style issues.
  src/app/business/block/create-host/create-host.component.html
  src/app/i18n/en/keyID.json
  src/app/i18n/zh/keyID.json
Labels: DAITO, bug

#231 Added ESXi OS type and added Host to Main Menu description
  src/app/app.component.ts
  src/app/business/block/create-host/create-host.component.ts
Labels: DAITO, enhancement

#218 Updated the ReadMe with development setup steps
  README.md
Labels: enhancement

#234 [FEATURE] Fixes #213. Added modify feature for user-added host.
  src/app/app-routing.module.ts
  src/app/business/block/hosts.component.ts
  src/app/business/block/hosts.service.ts
  src/app/business/block/modify-host/az-resolver.service.ts
  src/app/business/block/modify-host/host-resolver.service.ts
  src/app/business/block/modify-host/modify-host.component.html
  src/app/business/block/modify-host/modify-host.component.ts
  src/app/business/block/modify-host/modify-host.module.ts
Labels: DAITO, feature

#241 Fixes #240. Fixed Delete bucket and object to match changed backend response
  src/app/business/block/bucket-detail/bucket-detail.component.ts
  src/app/business/block/buckets.component.ts
Labels: DAITO, bug

#238 Fixes #236. Fixed the null value sent in description field in Create snapshot/acl
  src/app/business/block/file-share-detail/file-share-detail.component.ts
  src/app/business/block/fileShare.component.ts
  src/app/business/block/volume-detail/snapshot-list/snapshot-list.component.ts
  src/app/business/block/volumeGroup.component.ts
  src/app/business/block/volumeList.component.ts
Labels: DAITO, bug

#237 Fixes #235. Fixed the Create Replication Dialog layout issue.
  src/app/business/block/volumeList.html
Labels: DAITO, bug

#242 Implement replication between different buckets and within the same bucket
  src/app/business/block/bucket-detail/bucket-detail.component.html
  src/app/business/block/bucket-detail/bucket-detail.component.ts
  src/app/business/block/bucket-detail/bucket-detail.module.ts
  src/app/business/block/buckets.service.ts
Labels: DAITO, feature

#251 Fixes #224 and #248. Fixed listing of objects in a bucket and last modified time.
  src/app/business/block/bucket-detail/bucket-detail.component.html
  src/app/business/block/bucket-detail/bucket-detail.component.ts
  src/app/business/block/buckets.component.ts
Labels: DAITO, bug

#255 Fixes #254. Fixed delete bucket fail even if bucket empty.
  src/app/business/block/buckets.component.ts
Labels: DAITO, bug

#253 acl component and object-acl component
  proxy.conf.json
  src/app/app-routing.module.ts
  src/app/app.component.ts
  src/app/business/block/bucket-detail/acl/acl.component.html
  src/app/business/block/bucket-detail/acl/acl.component.ts
  src/app/business/block/bucket-detail/acl/acl.module.ts
  src/app/business/block/bucket-detail/bucket-detail.component.html
  src/app/business/block/bucket-detail/bucket-detail.component.ts
  src/app/business/block/bucket-detail/bucket-detail.module.ts
  src/app/business/block/bucket-detail/object-acl/object-acl.component.html
  src/app/business/block/bucket-detail/object-acl/object-acl.component.ts
  src/app/business/block/bucket-detail/object-acl/object-acl.module.ts
  src/app/business/block/buckets.service.ts
Labels: DAITO, feature

#257 Fixes #256. Fixed Enable Versioning and Encryption API calls failing …
  src/app/business/block/buckets.component.ts
Labels: DAITO, bug

#264 modify bug
  src/app/app.component.ts
  src/app/business/block/bucket-detail/acl/acl.component.html
  src/app/business/block/bucket-detail/acl/acl.component.ts
  src/app/business/block/bucket-detail/bucket-detail.component.ts
  src/app/business/block/bucket-detail/object-acl/object-acl.component.html
  src/app/business/block/buckets.html
Labels: DAITO, bug

#259 Fixes #258. Fixed object name not visible in bucket folder.
  src/app/business/block/bucket-detail/bucket-detail.component.ts
Labels: DAITO, bug

#269 add download message
  src/app/app.component.html
  src/app/app.component.ts
  src/app/business/block/bucket-detail/bucket-detail.component.ts
Labels: bug

#270 Modify the lifecycle bug
  src/app/business/block/bucket-detail/lifeCycle/lifeCycle.component.ts
Labels: bug

#275 Fixes #272. Added validation for bucket name while creating.
  src/app/business/block/buckets.component.ts
Labels: DAITO, bug

#273 Fixes #271. Success and Error notifications are shown on bucket create success or error
  src/app/business/block/buckets.component.ts
Labels: DAITO, bug
