Repository sodafoundation/dashboard, pull requests merged in 2019-06, with the labels that each got.

#81 Added Orchestration services feature. Minor fixes in Monitor list page.
  .angular-cli.json
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.component.ts
  src/app/business/service/service.component.html
  src/app/business/service/service.module.ts
  src/app/business/services/create-instance/create-instance.component.css
  src/app/business/services/create-instance/create-instance.component.html
  src/app/business/services/create-instance/create-instance.component.ts
  src/app/business/services/dynamic-form/dynamic-form.component.css
  src/app/business/services/dynamic-form/dynamic-form.component.html
  src/app/business/services/dynamic-form/dynamic-form.component.ts
  src/app/business/services/instance-list/instance-list.component.css
  src/app/business/services/instance-list/instance-list.component.html
  src/app/business/services/instance-list/instance-list.component.ts
  src/app/business/services/services-list/services-list.component.css
  src/app/business/services/services-list/services-list.component.html
  src/app/business/services/services-list/services-list.component.ts
  src/app/business/services/services-routing.module.ts
  src/app/business/services/services.component.html
  src/app/business/services/services.component.ts
  src/app/business/services/services.module.ts
  src/app/business/services/workflow.service.ts
  src/assets/business/css/site.scss
Labels: enhancement

#93 Fixed #92. Url links in the Monitor list page not working.
  src/app/business/monitor/monitor-list/monitor-list.component.html
Labels: bug

#96 Added auth token header to the create service instance api.
  src/app/business/services/dynamic-form/dynamic-form.component.ts
  src/app/business/services/services-list/services-list.component.ts
  src/app/business/services/workflow.service.ts
Labels: enhancement

#113 Fixes #106. Added the nginx conf changes to entrypoint and api calls.…
  entrypoint.sh
  src/app/business/services/services-list/services-list.component.html
  src/app/business/services/services-list/services-list.component.ts
  src/app/business/services/workflow.service.ts
Labels: bug

#116 Fixes #99. Changed the response type of upload response to text.
  src/app/business/monitor/config/config.component.ts
  src/app/business/monitor/monitor.service.ts
Labels: bug

#117 Revert changes made in #113 to fix nginx config.
  entrypoint.sh
  src/app/business/services/workflow.service.ts
Labels: CAPRI

#120 Fixes #108. Added different descriptions for the resources.
  src/app/business/block/block.html
  src/app/i18n/en/keyID.json
  src/app/i18n/zh/keyID.json
Labels: enhancement

#123 fixes issue#89
  src/app/business/block/bucket-detail/lifeCycle/lifeCycle.component.html
  src/app/business/block/bucket-detail/lifeCycle/lifeCycle.component.ts
Labels: CAPRI

#127 Added host_info and profile to orchestration volume provision.
  src/app/business/services/dynamic-form/dynamic-form.component.html
  src/app/business/services/dynamic-form/dynamic-form.component.ts
  src/app/business/services/workflow.service.ts
Labels: enhancement

#135 Update copyright in license description
  Dockerfile
  Makefile
  entrypoint.sh
  image_builder.sh
Labels: CAPRI

#142 Added i18n support for create service instance dynamic form.
  src/app/business/services/dynamic-form/dynamic-form.component.ts
  src/app/i18n/en/dynamicForm.json
  src/app/i18n/zh/dynamicForm.json
  src/app/shared/shared.config.ts
Labels: bug

#145 Fixed #144. Added the loading animations to the services feature.
  src/app/business/services/create-instance/create-instance.component.ts
  src/app/business/services/dynamic-form/dynamic-form.component.ts
  src/app/business/services/instance-list/instance-list.component.ts
  src/app/business/services/services-list/services-list.component.ts
  src/app/business/services/workflow.service.ts
Labels: bug
