Repository sodafoundation/dashboard, pull requests merged in 2019-11, with the labels that each got.

#210 [FEATURE] Fixes #205. Added Host management feature.
  src/app/app-routing.module.ts
  src/app/business/block/block.component.ts
  src/app/business/block/block.html
  src/app/business/block/block.module.ts
  src/app/business/block/create-host/create-host.component.html
  src/app/business/block/create-host/create-host.component.ts
  src/app/business/block/create-host/create-host.module.ts
  src/app/business/block/host-detail/host-detail.component.html
  src/app/business/block/host-detail/host-detail.component.ts
  src/app/business/block/host-detail/host-detail.module.ts
  src/app/business/block/hosts.component.html
  src/app/business/block/hosts.component.ts
  src/app/business/block/hosts.module.ts
  src/app/business/block/hosts.service.ts
  src/app/i18n/en/keyID.json
  src/app/i18n/zh/keyID.json
  src/assets/business/css/site.scss
Labels: Daito, feature

#212 [Feature] Fixes #209. Added Host attach and Detach to Volume.
  src/app/business/block/attach.service.ts
  src/app/business/block/volume-detail/attachment-list/attachment-list.component.html
  src/app/business/block/volume-detail/attachment-list/attachment-list.component.ts
  src/app/business/block/volume-detail/volume-detail.component.html
  src/app/business/block/volume-detail/volume-detail.module.ts
  src/app/business/block/volumeList.component.ts
  src/app/business/block/volumeList.html
  src/app/business/block/volumeList.module.ts
  src/app/i18n/en/keyID.json
  src/app/i18n/zh/keyID.json
  src/assets/business/css/site.scss
Labels: Daito, enhancement, feature

#211 [FEATURE] Fixes #199 . Added SSE feature on buckets.
  src/app/business/block/buckets.component.ts
  src/app/business/block/buckets.html
  src/app/business/block/buckets.module.ts
  src/app/business/block/buckets.service.ts
  src/assets/business/css/site.scss
Labels: Daito, feature

#217 [Feature] Fixes #201. Added versioning at bucket level.
  src/app/business/block/buckets.component.ts
  src/app/business/block/buckets.html
  src/app/business/block/buckets.service.ts
Labels: Daito, feature

#208 Fixes #206. Added changes to create profile as per refactored API
  src/app/business/profile/createProfile/createProfile.component.html
  src/app/business/profile/createProfile/createProfile.component.ts
  src/app/i18n/en/keyID.json
  src/app/i18n/zh/keyID.json
Labels: Daito, enhancement

#207 PUT/GET/DELETE lifecycle configurations
  src/app/business/block/bucket-detail/bucket-detail.component.ts
  src/app/business/block/bucket-detail/lifeCycle/lifeCycle.component.ts
  src/app/business/home/home.component.ts
  src/app/shared/utils/consts.ts
Labels: Daito

#216 Fixes #214. User can select the host from available list in volume provision service
  src/app/business/services/dynamic-form/dynamic-form.component.html
  src/app/business/services/dynamic-form/dynamic-form.component.ts
  src/app/business/services/services.module.ts
Labels: Daito, enhancement
