Repository sodafoundation/dashboard, pull requests merged in 2020-10, with the labels that each got.

#452 [Hw-SFS FileShare Support] Implement Hw Cloud SFS FileShare Dashboard Support for Multi-Cloud
  src/app/business/block/cloud-file-share/cloud-file-share.component.ts
  src/app/business/block/cloud-file-share/create/cloud-file-share-create.component.html
  src/app/business/block/cloud-file-share/create/cloud-file-share-create.component.ts
  src/app/business/block/cloud-file-share/create/cloud-file-share-create.module.ts
  src/app/business/block/cloud-file-share/modify/cloud-file-share-modify.component.ts
  src/app/business/home/home.component.ts
  src/app/shared/utils/consts.ts
Labels: enhancement, feature

#457 Fixed issues with Huawei FS create form. Fixes #453 and #454
  src/app/business/block/cloud-file-share/create/cloud-file-share-create.component.html
  src/app/business/block/cloud-file-share/create/cloud-file-share-create.component.ts
  src/app/business/block/cloud-file-share/create/cloud-file-share-create.module.ts
Labels: bug-fix

#456 Add support for Huawei EVS to SODA Dashboard multicloud block service
  src/app/business/block/cloud-block-service/cloud-block-service.component.html
  src/app/business/block/cloud-block-service/cloud-block-service.component.ts
  src/app/business/block/cloud-block-service/create/cloud-volume-create.component.html
  src/app/business/block/cloud-block-service/create/cloud-volume-create.component.ts
  src/app/business/block/cloud-block-service/modify/cloud-volume-modify.component.html
  src/app/business/block/cloud-block-service/modify/cloud-volume-modify.component.ts
  src/app/shared/utils/consts.ts
Labels: enhancement
