Repository sodafoundation/dashboard, pull requests merged in 2020-01, with the labels that each got.

#280 added yig icon
  src/app/shared/utils/consts.ts
  src/assets/business/images/common/yig.png
Labels: DAITO, enhancement

#278 Register displays input based on the type value
  src/app/business/home/home.component.html
  src/app/business/home/home.component.ts
Labels: enhancement

#279 Remove versioning feature links from the front end.
  src/app/business/block/buckets.html
Labels: DAITO

#289 Development branch merge into Matser for Daito v0.10.0 release
  src/app/business/block/buckets.html
Labels: DAITO
