Repository sodafoundation/dashboard, pull requests merged in 2021-06, with the labels that each got.

#599 Use shared modules to inject dependencies. Remove duplication of framework component and common modules in all modules.
  src/app/app.module.ts
  src/app/business/ak-sk/ak-sk.module.ts
  src/app/business/block/block.module.ts
  src/app/business/block/bucket-detail/acl/acl.module.ts
  src/app/business/block/bucket-detail/bucket-detail.module.ts
  src/app/business/block/bucket-detail/lifeCycle/lifeCycle.module.ts
  src/app/business/block/bucket-detail/object-acl/object-acl.module.ts
  src/app/business/block/buckets.module.ts
  src/app/business/block/cloud-block-service/cloud-block-service.module.ts
  src/app/business/block/cloud-block-service/create/cloud-volume-create.module.ts
  src/app/business/block/cloud-block-service/modify/cloud-volume-modify.module.ts
  src/app/business/block/cloud-file-share/cloudFileShare.module.ts
  src/app/business/block/cloud-file-share/create/cloud-file-share-create.module.ts
  src/app/business/block/cloud-file-share/modify/cloud-file-share-modify.module.ts
  src/app/business/block/create-file-share/create-file-share.module.ts
  src/app/business/block/create-host/create-host.module.ts
  src/app/business/block/create-volume/create-volume.module.ts
  src/app/business/block/file-share-detail/file-share-detail.module.ts
  src/app/business/block/fileShare.module.ts
  src/app/business/block/host-detail/host-detail.module.ts
  src/app/business/block/hosts.module.ts
  src/app/business/block/modify-host/modify-host.module.ts
  src/app/business/block/volume-detail/volume-detail.module.ts
  src/app/business/block/volume-group-detail/volume-group-detail.module.ts
  src/app/business/block/volumeGroup.module.ts
  src/app/business/block/volumeList.module.ts
  src/app/business/dataflow/dataflow.module.ts
  src/app/business/dataflow/migration-detail/migration-detail.module.ts
  src/app/business/dataflow/migration.module.ts
  src/app/business/dataflow/replication-detail/replication-detail.module.ts
  src/app/business/dataflow/replication.module.ts
  src/app/business/delfin/delfin.module.ts
  src/app/business/delfin/modify-storage/modify-storage.module.ts
  src/app/business/delfin/performance-monitor/performance-monitor.module.ts
  src/app/business/delfin/register-storage/register-storage.module.ts
  src/app/business/delfin/storage-details/storage-details.module.ts
  src/app/business/help/help.module.ts
  src/app/business/home/home.module.ts
  src/app/business/identity/identity.module.ts
  src/app/business/identity/tenantDetail/tenantDetail.module.ts
  src/app/business/identity/tenantList.module.ts
  src/app/business/identity/userDetail/userDetail.module.ts
  src/app/business/identity/userList.module.ts
  src/app/business/profile/createProfile/createProfile.module.ts
  src/app/business/profile/modifyProfile/modifyProfile.module.ts
  src/app/business/profile/profile.module.ts
  src/app/business/profile/storage-pools-table/storage-pools-table.module.ts
  src/app/business/resource/resource.module.ts
  src/app/business/services/services.module.ts
  src/app/shared/shared.module.ts
Labels: Optimization-CleanUp

#603 [Delfin UI] Added support for NetApp driver. Updated resource support matrix.
  src/app/shared/utils/consts.ts
Labels: enhancement

#600 [Feature] Added support for custom storage service plans.
  entrypoint.sh
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.component.ts
  src/app/business/block/bucket-detail/bucket-detail.component.html
  src/app/business/block/bucket-detail/bucket-detail.component.ts
  src/app/business/block/buckets.component.ts
  src/app/business/block/buckets.html
  src/app/business/block/buckets.service.ts
  src/app/business/dataflow/migration-detail/migration-detail.component.html
  src/app/business/dataflow/migration-detail/migration-detail.component.ts
  src/app/business/dataflow/migration.component.ts
  src/app/business/dataflow/migration.html
  src/app/business/home/home.component.ts
  src/app/business/service-plan/service-plan.component.ts
  src/app/business/service-plan/service-plan.html
  src/app/business/service-plan/service-plan.module.ts
  src/app/business/service-plan/service-plan.service.ts
  src/app/shared/shared.config.ts
  src/app/shared/shared.module.ts
  src/app/shared/utils/consts.ts
  src/assets/business/css/site.scss
  src/assets/data/runtime.json
Labels: feature

#607 Removed the bucket field from backend registration form for IBM COS and Alibaba
  src/app/business/home/home.component.ts
Labels: enhancement

#608 Updated the overall performance monitoring grafana dashboard embedded url
  src/app/business/delfin/performance-monitor/performance-monitor.component.html
  src/app/business/delfin/performance-monitor/performance-monitor.component.ts
Labels: enhancement

#610 Updated masking view UI as per changes made to backend. Added util for creating queryParams
  src/app/business/delfin/delfin-resolver.service.ts
  src/app/business/delfin/delfin.service.ts
  src/app/business/delfin/masking-views/masking-views.component.html
  src/app/business/delfin/masking-views/masking-views.component.ts
  src/app/business/delfin/storages/storages.component.ts
  src/app/shared/utils/utils.ts
  src/assets/business/css/site.scss
Labels: enhancement

#614 [Service Plan UI] Added fixes for replacing occurrence of `Tier`. Fixes for remove buttons not hidden and incorrect display of Sidebar.
  src/app/business/service-plan/service-plan.component.ts
  src/app/business/service-plan/service-plan.html
Labels: bug-fix

#616 [Service Plan UI] Fixed the issue of service plan enabled in dashboard even when the installer flag is set to false.
  src/app/shared/shared.config.ts
Labels: bug-fix
