Repository sodafoundation/dashboard, pull requests merged in 2021-09, with the labels that each got.

#631 Removed the Ubuntu16 run from the CI
  .github/workflows/ci.yml
Labels: bug-fix

#630 [Delfin UI] Updated the masking views UI. Added support for resource groups
  src/app/business/delfin/delfin.service.ts
  src/app/business/delfin/masking-views/masking-views.component.html
  src/app/business/delfin/masking-views/masking-views.component.ts
  src/app/business/delfin/storage-details/storage-details.module.ts
  src/app/business/delfin/storage-hosts/storage-hosts.component.html
  src/app/business/delfin/storage-hosts/storage-hosts.component.ts
  src/assets/business/css/site.scss
Labels: enhancement

#634 update package.json
  package.json
Labels: Low Priority, soda-hackathon-2021
